### ISSUE TITLE
thumb

### ISSUE THREAD

**Issue by 530l** [litao0621/nifty-slider#11]
niftySlider.setThumbWidthAndHeight(6.dp, 22.dp, 30.dp)
            niftySlider.hideThumb(false)
            niftySlider.addOnSliderTouchStartListener {
                niftySlider.showThumb()
                binding.stateText.text = "Start Tracking Touch"
            }
            niftySlider.addOnSliderTouchStopListener {
                niftySlider.hideThumb()
                binding.stateText.text = "Stop Tracking Touch"
            }
大佬，这样有bug，thumb  还是圆的，不是我设置的那个大小

**Comment by litao0621** [comment]
v1.4.7 中修复了此问题 ，有其他问题随时提。
