### ISSUE TITLE
这种效果可以实现吗？

### ISSUE THREAD

**Issue by guozhiqiang123** [litao0621/nifty-slider#13]
![image](https://github.com/litao0621/nifty-slider/assets/20378988/a89b76ae-3c9e-4d44-b23c-1a081c68486c)

**Comment by litao0621** [comment]
v1.4.7 中添加了此效果，样例中的最后一个添加了此效果，详细实现查看 [这里](https://github.com/litao0621/nifty-slider/blob/main/sample/src/main/java/com/litao/niftyslider/fragment/IndicatorStyle1Fragment.kt)
