### ISSUE TITLE
优化问题

### ISSUE THREAD

**Issue by ZJFCany** [litao0621/nifty-slider#16]
1.hapticFeedbackEnabled=true  在部分手机上不生效    我的是huawei
2.ITEffect 无法叫文字设置在中间 center

**Comment by ZJFCany** [comment]
我想做的是一种滑块验证效果  但是滑块超出了左右两侧边界

**Comment by litao0621** [comment]
1. hapticFeedbackEnabled 是直接使用的系统方法，大概率和你手机的相关设置可能有关，我这边也排查下
2. ITEffect 只提供了两侧添加text和icon的功能，没明白在中间设置是什么意思，或着你可以提供一个交互图； 或着你也可以像ITEffect 一样继承BaseEffect 在滑块，轨道的绘制前后自己去处理绘制逻辑
3. 可以使用thumbWithinTrackBounds属性来让滑块保持在滑轨内，你可以看WeReadDemoFragment 中滑块就在滑轨内，看下是否满足你的需求

**Comment by ZJFCany** [comment]
当滑块的宽高大于轨道的高   这时候  滑块就会超出轨道

**Comment by ZJFCany** [comment]
![1724031323171](https://github.com/user-attachments/assets/228baa68-1d3f-478e-9d75-a85fbad14e3c)
回复问题 2

**Comment by litao0621** [comment]
v2.0.1中
修复了 thumbWithinTrackBounds 属性设置后仍然会超出滑轨的问题；
添加了default thumb添加icon的功能；
添加了你发的交互图对应的[demo](https://github.com/litao0621/nifty-slider/blob/main/sample/src/main/java/com/litao/niftyslider/fragment/SlidingVerificationDemoFragment.kt),使用[VerificationEffect](https://github.com/litao0621/nifty-slider/blob/main/sample/src/main/java/com/litao/niftyslider/effect/VerificationEffect.kt)将文字绘制到滑轨中心，由于此功能并不属于该控件应该去处理的，所以此效果只防治到了sample中，如果控件上还有类似光效及其他元素，可以在VerificationEffect的基础上自行修改；

如有其他问题可以在此issues 上继续提交。

**Comment by litao0621** [comment]
震动的问题在v2.0.1版本中添加了 `ignoreGlobalHapticFeedbackSetting` 属性，来控制震动是否跟随系统设置，默认不跟随，开启后会忽略系统设置，即使在系统设置中关闭了震动，应用中仍然会响应震动（由于系统相关限制，只对系统API < 33 的系统生效）

**Comment by ZJFCany** [comment]
当去掉  stepSize 时   hapticFeedbackEnabled=true  不生效

**Comment by litao0621** [comment]
震动只会在设置了stepSize后启用，你是希望正常滑动也一直震动吗，这样有点不符合正常的交互，你如果希望这样的话可以在`OnValueChangeListener`的回调中自己调用 `performHapticFeedback`控制哪些进度需要震动。

**Comment by ZJFCany** [comment]
huawei手机还是不会震动 mate30pro   harmonyOS4.2.0  Android 12  
未开启  系统触感反馈

**Comment by litao0621** [comment]
你试下 WeReadDemoFragment 这个demo中的第二个slider 有震动效果吗，我也试着找个一样的手机看下。

**Comment by litao0621** [comment]
我这里只找到一台mate30pro harmonyOS4.2.0 ，测试是正常的（仅stepSize>0时启用）。
震动的内部实现是使用`view.performHapticFeedback`,如果可以的话可以帮忙测试下performHapticFeedback设置不同的feedbackConstant 看下是否全部无效，是否与feedbackConstant有关。也欢迎提交pull requests

**Comment by ZJFCany** [comment]
测试后发现还是 和  stepSize 有关   我没有设置stepSize   但是我在代码中设置performHapticFeedback 这样华为就不会震动 红米可以
但是我设置了stepSize  震动都生效

**Comment by litao0621** [comment]
可以发个代码片段吗,我看下你是如何设置的。
控件内部震动的条件是 stepSize >0 && hapticFeedbackEnabled=true 如果需要忽略系统震动设置还需要 ignoreGlobalHapticFeedbackSetting=true. 需要启用震动你需要满足以上条件。

如果你在代码中自己调用performHapticFeedback，那就先关闭控件中的震动逻辑 hapticFeedbackEnabled = false ,然后自行调用，如果需要忽略系统设置就可以像以下代码
``` kotlin
View.performHapticFeedback(
                    HapticFeedbackConstants.VIRTUAL_KEY,
                    HapticFeedbackConstants.FLAG_IGNORE_GLOBAL_SETTING
                )
```

**Comment by ZJFCany** [comment]
按照你这个是没问题的    我之前在代码中是这样的
View.performHapticFeedback(
                    HapticFeedbackConstants.VIRTUAL_KEY
                )
在布局中是
android:hapticFeedbackEnabled="true"
app:ignoreGlobalHapticFeedbackSetting="true"
这样就不行

**Comment by litao0621** [comment]
哦，应该是performHapticFeedback 需要加个忽略系统设置的flag(这个只在api < 33生效)，那有其他问题再随时提哈，感谢反馈😄

**Comment by ZJFCany** [comment]
非常感谢
