### ISSUE TITLE
仿抖音进度条

### ISSUE THREAD

**Issue by LinWangYan** [litao0621/nifty-slider#2]
没拖拽的时候进度条那个小球周围不光滑，好像有些像刺一样的在一圈射出来似的，由于demo里面仿抖音的那个页面背景是黑色的，不是明显，如果把页面背景改为白色就能看清了这个bug了

**Comment by litao0621** [comment]
fixed in v1.4.2

**Comment by litao0621** [comment]
fixed in v1.4.2
