### ISSUE TITLE
设置阴影，滑动时会有很明显的毛刺

### ISSUE THREAD

**Issue by earthOfSun** [litao0621/nifty-slider#3]

**Comment by litao0621** [comment]
使用的是v1.4.2版本吗？

**Comment by earthOfSun** [comment]
是的

**Comment by litao0621** [comment]
来信已收到，我会尽快回复你的！

**Comment by litao0621** [comment]
可以发我一个demo apk吗
顺便提供下设备型号，版本，使用时的样例xml布局+代码，最好截张有问题的图

**Comment by earthOfSun** [comment]
<com.litao.slider.NiftySlider
        android:id="@+id/mSlide"
        style="@style/theaterSlider"
        android:layout_marginHorizontal="@dimen/dp_28"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/dp_16"
        android:layout_marginBottom="@dimen/dp_11"
        android:hapticFeedbackEnabled="true"
        android:value="100"
        android:valueFrom="100"
        android:valueTo="140"
        app:enableDrawHalo="false"
        app:thumbElevation="3dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/mTvTitle"
        app:thumbText="100"
        app:thumbTextColor="@color/color_484848"
        app:thumbTextSize="@dimen/sp_10"
        app:thumbWidth="@dimen/dp_27"
        app:thumbWithinTrackBounds="true"
        app:trackColor="#FFDEDEDE"
        app:trackColorInactive="#FFF1F1F1"
        app:trackCornersRadius="@dimen/dp_25"
        app:trackHeight="@dimen/dp_28" />

**Comment by litao0621** [comment]
你截一张图我看下是什么样子的毛刺，如果不使用动画变换的话你可以先使用1.4.1。

**Comment by earthOfSun** [comment]
我想复现又复现不了了

**Comment by litao0621** [comment]
> 我想复现又复现不了了

确实存在些问题，在1.4.3中修复了一些阴影的兼容性问题，对阴影逻辑进行了优化，可以更新到1.4.3，后面如还有类似问题，再打开此问题。
