### ISSUE TITLE
抖音seek效果 thumb 为圆球时拖动到最前或者最后会被切割 

### ISSUE THREAD

**Issue by jiaweio** [litao0621/nifty-slider#7]
你好  很感谢作者提供的这个滑动框架 
    1、如标题描述我在使用仿抖音效果时如果将thumb 为圆球，拖动圆球至最左或者最右圆球会出现被切割的情况（thumbWithinTrackBounds已经设置为true），一开始以为是我布局外层包裹的父控件设置的padding 导致的问题，所以将父控件设置了clipToPadding 和 clipChildren 都为false，依旧没能解决问题（我尝试了demo的tiktokFragment复现了），所以想请教下作者有什么解决思路
    2、我发现 NiftySlider 控件设置 paddingTop 或者 paddingBottom 进度条永远会显示在中间，个人认为应该是thumb需要显示空间不然会被切割，如果我需要将 NiftySlider  进度条准确的摆放在某个控件的上面（进度条紧贴某控件顶部），有什么可以尝试的方法吗  
    针对第一个问题 我代码设置如下图所示 
    
![image](https://github.com/litao0621/nifty-slider/assets/21191820/06ae11cf-b220-4b95-b541-44e48599d56c)

**Comment by litao0621** [comment]
问题1:
控件的阴影，动画过程的放大确实可能超出视图区域，目前建议添加左右padding来解决，外层尽量使用可叠加的viewgroup,如果
`ConstraintLayout`，`FrameLayout` 来更好的修正设置padding后你的其他view位置的处理。

问题2:
目前padding top/bottom 确实不会按照原有逻辑执行,可以直接使用trackInnerVPadding来均匀的调整上下间距，设置后只会均分到上下部分，也是为了能让内部的shadow.thumb.halo在不同场景下更好的展示，我认为可以将上下的padding替换为marging 来处理上下的间距，当前我觉得没有什么场景来说必须要添加控件的padding top/bottom才能处理。

如果想准确定位到某个到某个位置的话，可以想下面这样，`ConstraintLayout`中，先添加一条基准线，来准确的定位到你想要要放置到位置，再让slider 约束在这条基准线的上下，因为进度条会居中绘制，也会准确的置于基准线上达到你想要的效果。
``` xml
<com.litao.slider.NiftySlider
        android:id="@+id/slider"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingLeft="16dp"
        android:paddingRight="16dp"
        android:value="0.5"
        app:enableDrawHalo="false"
        app:layout_constraintTop_toTopOf="@+id/guideline"
        app:layout_constraintBottom_toBottomOf="@+id/guideline"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:thumbRadius="16dp"
        app:thumbWithinTrackBounds="true"
        app:trackHeight="3dp"
        app:trackInnerHPadding="0dp" />

    <TextView
        android:id="@+id/guideline"
        android:layout_width="0dp"
        android:layout_height="1dp"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:orientation="horizontal"
        app:layout_constraintBottom_toTopOf="@+id/bottom_bar_layout"
        />
```

问题1中裁剪的问题我后面会想办法修改下处理方式，让使用者减少配置。
有其他使用问题都可以随时提。

**Comment by jiaweio** [comment]
> 问题1: 控件的阴影，动画过程的放大确实可能超出视图区域，目前建议添加左右padding来解决，外层尽量使用可叠加的viewgroup,如 `ConstraintLayout`，`FrameLayout` 来更好的修正设置padding后你的其他view位置的处理。
> 
> 问题2: 目前padding top/bottom 确实不会按照原有逻辑执行,可以直接使用trackInnerVPadding来均匀的调整上下间距，设置后只会均分到上下部分，也是为了能让内部的shadow.thumb.halo在不同场景下更好的展示，我认为可以将上下的padding替换为marging 来处理上下的间距，当前我觉得没有什么场景来说必须要添加控件的padding top/bottom才能处理。
> 
> 如果想准确定位到某个到某个位置的话，可以想下面这样，`ConstraintLayout`中，先添加一条基准线，来准确的定位到你想要要放置到位置，再让slider 约束在这条基准线的上下，因为进度条会居中绘制，也会准确的置于基准线上达到你想要的效果。
> 
> ```
> <com.litao.slider.NiftySlider
>         android:id="@+id/slider"
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:paddingLeft="16dp"
>         android:paddingRight="16dp"
>         android:value="0.5"
>         app:enableDrawHalo="false"
>         app:layout_constraintTop_toTopOf="@+id/guideline"
>         app:layout_constraintBottom_toBottomOf="@+id/guideline"
>         app:layout_constraintLeft_toLeftOf="parent"
>         app:layout_constraintRight_toRightOf="parent"
>         app:thumbRadius="16dp"
>         app:thumbWithinTrackBounds="true"
>         app:trackHeight="3dp"
>         app:trackInnerHPadding="0dp" />
> 
>     <TextView
>         android:id="@+id/guideline"
>         android:layout_width="0dp"
>         android:layout_height="1dp"
>         app:layout_constraintLeft_toLeftOf="parent"
>         app:layout_constraintRight_toRightOf="parent"
>         android:orientation="horizontal"
>         app:layout_constraintBottom_toTopOf="@+id/bottom_bar_layout"
>         />
> ```
> 
> 问题1中裁剪的问题我后面会想办法修改下处理方式，让使用者减少配置。 有其他使用问题都可以随时提。

好的   我这边试试   感谢作者提供的思路
