### ISSUE TITLE
进度条动画时，读取进度条数据为上一次设置的数据

### ISSUE THREAD

**Issue by MatrixLau** [litao0621/nifty-slider#8]
当```setValue```时打开了动画开关，紧随其后```getValue```获取到的是上一次```setValue```的值

**Comment by MatrixLau** [comment]
在不确定该问题是**特性**还是**BUG**前，目前比较好的处理方法是在```OnValueChange```，判断**fromUser**为*false*时，进行原本紧接着```setValue```的需要```getValue```的操作。

**Comment by litao0621** [comment]
内部记录的progress value始终是当前真实的视觉感知进度，开启动画后progress value也会随着动画的执行而改变，而不是直接修改到目标进度，这样是为了保持视图的所有状态和value始终是对应的。

如果像下面这样使用，获取到的确实不会是修改后的值，因为动画还没有启动，progress value也不会修改，像下面的代码未开启动画时会以一条消息进行发送，代码也会顺序执行，也可实时拿到变更后的值，但开启动画后就被拆分为了多条消息，会优先执行getValue。setValue则会在Animator Change的过程中不断以独立消息的形式发送到消息队列的尾部。

``` kotlin
//起始value是 0 
slider.setValue(value = 100f, animated = true)
val value = slider.value
//此时value任然是0

```

如果你想随后立即获取，为什么不直接获取你设置的值呢
``` kotlin
val targetValue = 100f
slider.setValue(value = targetValue animated = true)

//val value = slider.value  修改为直接使用targetValue
val value =  targetValue

```

也可以通过`OnValueChange `的来实时拿到当前的progress value

``` kotlin
slider.setOnValueChangeListener{ slider, value, fromUser ->
    val value =  targetValue
 }

```



我还不太明白具体的使用场景，你可以描述下这样操作的具体场景吗，如果确实有无法满足的合理场景，我可以提供相关功能的支持。

**Comment by MatrixLau** [comment]
> 内部记录的progress value始终是当前真实的视觉感知进度，开启动画后progress value也会随着动画的执行而改变，而不是直接修改到目标进度，这样是为了保持视图的所有状态和value始终是对应的。
> 
> 如果像下面这样使用，获取到的确实不会是修改后的值，因为动画还没有启动，progress value也不会修改，像下面的代码未开启动画时会以一条消息进行发送，代码也会顺序执行，也可实时拿到变更后的值，但开启动画后就被拆分为了多条消息，会优先执行getValue。setValue则会在Animator Change的过程中不断以独立消息的形式发送到消息队列的尾部。
> 
> ```kotlin
> //起始value是 0 
> slider.setValue(value = 100f, animated = true)
> val value = slider.value
> //此时value任然是0
> ```
> 
> 如果你想随后立即获取，为什么不直接获取你设置的值呢
> 
> ```kotlin
> val targetValue = 100f
> slider.setValue(value = targetValue animated = true)
> 
> //val value = slider.value  修改为直接使用targetValue
> val value =  targetValue
> ```
> 
> 也可以通过`OnValueChange `的来实时拿到当前的progress value
> 
> ```kotlin
> slider.setOnValueChangeListener{ slider, value, fromUser ->
>     //直接使用回调中的value
>  }
> ```
> 
> 我还不太明白具体的使用场景，你可以描述下这样操作的具体场景吗，如果确实有无法满足的合理场景，我可以提供相关功能的支持。

不直接获取setValue的值是因为，后面调用getValue的一个要将各进度条数据还有其他数据组装成一个列表再在发命令的时候需要用到这个复杂的列表

**Comment by litao0621** [comment]
那目前直接使用你自己设定的目标值就可以了，下一版本发布后会添加一个[进度动画结束的回调][1]，进度执行到目标进度后会进行通知。


[1]:https://github.com/litao0621/nifty-slider/blob/main/slider/src/main/java/com/litao/slider/NiftySlider.kt#L251-L253

**Comment by MatrixLau** [comment]
> 那目前直接使用你自己设定的目标值就可以了，下一版本发布后会添加一个[进度动画结束的回调](https://github.com/litao0621/nifty-slider/blob/main/slider/src/main/java/com/litao/slider/NiftySlider.kt#L251-L253)，进度执行到目标进度后会进行通知。

好的 感谢

**Comment by litao0621** [comment]
已在v1.4.6 中添加[进度动画结束的回调](https://github.com/litao0621/nifty-slider/blob/main/slider/src/main/java/com/litao/slider/NiftySlider.kt#L251-L253)，有其他问题随时提。
