### ISSUE TITLE
支持垂直？

### ISSUE THREAD

**Issue by LazyIonEs** [litao0621/nifty-slider#9]
现在有个需求，需要垂直的，中间thumb可显示数字，使用此库用`android:rotation="270"`发现thumb内文字也被旋转，请问可适配下垂直方向，或请教下解决思路

**Comment by litao0621** [comment]
目前没有做垂直方向的支持，我最近会抽时间把这个功能加上。

**Comment by ANSWER21** [comment]
您好，请问目前支持垂直了嘛

**Comment by phoebewow** [comment]
等待垂直功能ing.....

**Comment by litao0621** [comment]
v2.0.0已支持垂直模式
由于issues.sonatype.org 被废弃了，涉及到一些账号的迁移工作，后续迁移完成会后立即上传到maven

**Comment by litao0621** [comment]
已经发布到maven仓库
